version: '3.9'

services:
  db1:
    image: postgres:13-alpine
    volumes:
      - db_python1:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=bank_transaction_db_1
    ports:
      - "6543:6543"
    networks:
      - projeto-network

  app1:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./bank:/bank
      - ./wait-for-it.sh:/wait-for-it.sh 
    command: >
      sh -c "python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db1
      - DB_NAME=bank_transaction_db_1
      - DB_USER=postgres
      - DB_PASSWORD=123456
    depends_on:
      - db1
    networks:
      - projeto-network

  db2:
    image: postgres:13-alpine
    volumes:
      - db_python2:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=bank_transaction_db_2
    ports:
      - "6544:6544"
    networks:
      - projeto-network

  app2:
    build: 
      context: .
    ports:
      - "8001:8001"
    volumes:
      - ./bank:/bank
      - ./wait-for-it.sh:/wait-for-it.sh 
    command: >
      sh -c "
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8001"
    environment:
      - DB_HOST=db2
      - DB_NAME=bank_transaction_db_2
      - DB_USER=postgres
      - DB_PASSWORD=123456
    depends_on:
      - db2
    networks:
      - projeto-network

  db3:
    image: postgres:13-alpine
    volumes:
      - db_python3:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=bank_transaction_db_3
    ports:
      - "6545:6545"
    networks:
      - projeto-network

  app3:
    build: 
      context: .
    ports:
      - "8002:8002"
    volumes:
      - ./bank:/bank
      - ./wait-for-it.sh:/wait-for-it.sh 
    command: >
      sh -c "
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8002"
    environment:
      - DB_HOST=db3
      - DB_NAME=bank_transaction_db_3
      - DB_USER=postgres
      - DB_PASSWORD=123456
    depends_on:
      - db3
    networks:
      - projeto-network

volumes:
  db_python1:
  db_python2:
  db_python3:

networks:
  projeto-network:
    driver: bridge

