# Generated by Django 5.0.6 on 2024-06-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='in_transaction',
            field=models.BooleanField(default=False),
        ),
    ]
