# Generated by Django 5.0.6 on 2024-06-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_in_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='in_transaction_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
