# Generated by Django 5.0.6 on 2024-07-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_client_is_staff_alter_client_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_joint_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='user_one',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='user_two',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
